### ISSUE TITLE
WinError 183 "file exists" with multiprocessing evaluator

### ISSUE THREAD

**Issue by BenjaminSchoemaker** [quaquel/EMAworkbench#105]
I am trying to perform experiments on a Vensim model using the multiprocessing evaluator (running on Windows 10 in Parellels) but it keeps giving me a WinError 183 "Cannot create a file when that file already exists". When looking at the root folder it appears that the issue comes from the tmp folders being created inside the root tmp folder. 
I tried setting the working folder to writable and changing the permissions but this did not help. 
Does anyone know a solution to this issue? 

![Schermafbeelding 2021-04-30 om 15 19 08](https://user-images.githubusercontent.com/77630491/116716360-f47fa180-a9d7-11eb-8a2e-2b16d47e70bd.png)

**Comment by quaquel** [comment]
I have never seen this before. Hust showing the error message is however not sufficient to even begin to figure out what is going on. In this case, I will need to see the basic code as well as how you have organised your directories.

**Comment by BenjaminSchoemaker** [comment]
Thanks for your fast response Jan. Code is given below. It works fine when I just use `results = perform_experiments(vensimModel,scenarios=10,policies=10)`.

`from __future__ import (division, unicode_literals, absolute_import,
                        print_function)
import math

# more or less default imports when using
# the workbench
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

from scipy.optimize import brentq

from ema_workbench import (TimeSeriesOutcome, perform_experiments,
                           RealParameter, ema_logging, RealParameter, ScalarOutcome, Constant, MultiprocessingEvaluator, save_results)

from ema_workbench.analysis import feature_scoring

from ema_workbench.connectors.vensim import VensimModel

def value_end(timeseries):
    return timeseries[-1]

if __name__ == "__main__":
    # turn on logging
    ema_logging.log_to_stderr(ema_logging.INFO)

    wd = 'C:\\' 
    vensimModel = VensimModel("ElectrificationModel", wd=wd, model_file='formal_model_new_cleaned_v13.vpmx')
    
    vensimModel.uncertainties = [RealParameter("Electricity market price projection 2030", 33.3, 71.9),
                                 RealParameter("ETS carbon price projection 2050", 40, 160),
                                 RealParameter("Gas market price projection 2030", 0.16, 0.319),
                                 RealParameter("Discount rate in percent", 10, 15),
                                 RealParameter("Retrofit investment cost per MW furnace", 300000, 1140000),
                                 RealParameter("Retrofit investment cost per MW compressor", 600000, 720000),
                                 RealParameter("Retrofit investment cost per MW boiler", 9710, 55000),
                                 RealParameter("Initial retrofit investment cost per MW furnace electric", 1140000, 3000000),
                                 RealParameter("Initial retrofit investment cost per MW compressor electric", 1000000, 2000000),
                                 RealParameter("Initial retrofit investment cost per MW boiler electric", 100000, 500000),
                                 RealParameter("Exogenous learning rate", 0, 0.00928),
                                 RealParameter("Export value of residual gas as a fraction of gas price", 0, 1),
                                 RealParameter("OPEX electric in percentage of investment costs", 1, 5),
                                 #RealParameter("Autonomous efficiency improvement", 0, 1),
                                 RealParameter("Efficiency improvements in conventional technologies", 0, 1),
                                 #RealParameter("Expected plant efficiency improvement 2050", 11, 22),
                                 RealParameter("Response speed to gas becoming residual", 5, 50),
                                 RealParameter("Response speed of investment share to costs ratio", 5, 50),
                                 RealParameter("Response speed of investment share to costs ratio (hybrid boiler)", 5, 50),
                                 RealParameter("Renewables share projection 2030", 40, 90), 
                                 RealParameter("Time interval between turnarounds", 5, 7), 
                                 RealParameter("Acquisition time hybrid boiler", 0.5, 1), 
                                 RealParameter("Economic lifetime boiler", 10, 20), 
                                 RealParameter("Economic lifetime compressor", 10, 20), 
                                 RealParameter("Economic lifetime furnace", 20, 30), 
                                 RealParameter("Maximum boiler hybridisation per year", 5, 10), 
                                 RealParameter("Percentage of boilers to become hybrid per year", 1, 5),
                                 #RealParameter("Initial gas demand other processes", 0, 25)
                                 ]
    vensimModel.levers = [RealParameter('"Base fee SDE++ per kWh"', 0.04, 0.14),
                          RealParameter("Carbon levy increase rate", 5.28, 21.12),
                          RealParameter("Carbon levy increase rate after 2030", 0, 21.12),
                          RealParameter("EHS grid connection costs", 1500000, 3000000),
                          RealParameter("Energy tax electricity", 0, 0.56),
                          RealParameter("Gas tax", 0.01281, 0.1281),
                          RealParameter("ODE electricity", 0, 0.4),
                          RealParameter("ODE gas", 0.0232, 0.232),
                          RealParameter("Variable transport tariff per kW per month furnace and compressor", 0, 1.23),
                          RealParameter("Variable transport tariff per kW per month boiler", 0, 2)]
    
    #vensimModel.outcomes = [TimeSeriesOutcome('Total emissions cracking in tonnes')]
    vensimModel.outcomes = [ScalarOutcome('Emissions 2050', variable_name='Total emissions cracking in tonnes', 
                                          function=value_end),
                            ScalarOutcome('Cum. production costs 2050', variable_name='Cumulative production costs', 
                                          function=value_end),
                            ScalarOutcome('Cum. policy costs 2050', variable_name='Cumulative policy costs', 
                                          function=value_end),
                            TimeSeriesOutcome('Total emissions cracking in tonnes'),
                            TimeSeriesOutcome('Production costs per tonne ethylene'),
                            TimeSeriesOutcome('Total policy costs per year')
                            ]
    
    with MultiprocessingEvaluator(vensimModel) as evaluator:
        results = evaluator.perform_experiments(scenarios=10,policies=10)
    
    #results = perform_experiments(vensimModel,scenarios=10,policies=10)
    
    save_results(results, 'results_test_10scenarios_10policies_2.tar.gz')`

I have tried different working directories, both on the local C disk (as I'm using Windows on Parallels) as on my Mac. I have also tried moving the Vensim model to the same directory as the Python file. Nonetheless, the issue keeps appearing. When looking at the tmp root folder it appears the issue arises from the evaluator trying to create tmp folders within the root folders with the same names as folders that were created earlier. 
![Schermafbeelding 2021-04-30 om 16 32 33](https://user-images.githubusercontent.com/77630491/116781335-7e844480-aa82-11eb-8056-a00c299fb928.png)

**Comment by quaquel** [comment]
I have edited your comment a bit to make it readable. A few quick comments on your code
- remove all imports you are not using
- the futures import is not needed anymore your code need not be compatible with python 2
- stick to forward slashes in path names
- read pep8 and apply it consistently. variable names for example should not be be camelCase but with an underscore. By sticking to pep8 conventions, you make your code much easier to understand for others.

I would reorganise your folders quite a bit and switch to forward slash based path names. My typical structure is

./src
    /model_folder
    /output_data_folder
    /figs_folder
    run_file.py

so have your vensim model in a folder located in the same directory as your .py file. See also the examples folder that comes with the workbench itself. If you have any questions about this, please let me know.

**Comment by BenjaminSchoemaker** [comment]
Thank you Jan! I will apply your suggestions.

**Comment by BenjaminSchoemaker** [comment]
I works now, having reorganized my folders, thank you!
