### ISSUE TITLE
load_results dtype issue

### ISSUE THREAD

**Issue by lvreedenburgh** [quaquel/EMAworkbench#106]
It seems to me that load_results converts dtype object to category, when results are saved again afterwards they will contain dtype category, which in turn causes an error when using load_results with the newly saved results containing category dtypes. This can be seen in the different experiments metadata files. As a workaround I can use .astype(str) to convert the dtypes back to object and use save_results. 

Thanks in advance!

After performing_experiments dtypes contain objects
![image](https://user-images.githubusercontent.com/45203207/120452633-a1ac5780-c392-11eb-8ac9-7c5d20cbdd15.png)

load_results -> save_results -> load_results again, but encountered error data type 'category' not understood
![image](https://user-images.githubusercontent.com/45203207/120452733-b4269100-c392-11eb-974f-3965e75b3828.png)

Experiments metadata original
![image](https://user-images.githubusercontent.com/45203207/120452810-c4d70700-c392-11eb-8c8e-d79addd12ed7.png)

Experiments metadata copy
![image](https://user-images.githubusercontent.com/45203207/120452859-cf919c00-c392-11eb-9bbf-bf25d2f5b1e9.png)

**Comment by quaquel** [comment]
fixed in 2.2
