### ISSUE TITLE
Index/reference mismatch on scenarios and policies

### ISSUE THREAD

**Issue by omarcastrejon** [quaquel/EMAworkbench#108]
Hi,
I am facing a little issue when trying to pass previously generated/sampled scenarios and policies to the perfom_experiments method. Let me elaborate.
As previously discussed (https://waterprogramming.wordpress.com/category/software/emaworkbench/), there are various ways of specifying scenarios and policies. One way is to directly pass the number of scenarios and policies to the perform_experiments method. However, with this method a new set of scenarios and policies are generated every time the method is called. An alternative option is to explicitly generate the scenarios and policies first, and then pass these to the method and thus avoid noise and instability (or maybe someone wants to use these instances again in the analysis). I opted for the latter within my analysis. To do this I am using the built-in sample.uncertainties and sample.levers methods and then I have passed these instances to the perform_experiments method. However, when the experiments are generated using the perform_experiments method the reference number for scenarios and policies does not match. Let me give you an hypothetical example:
* I decide to generate 50 scenarios and 5 policies.
* I generate the scenarios using the sample_uncertainties method and assign them a name (let's say 'scenarios').
* I generate the policies using the sample_levers method and assign them a name (let's say 'policies').
* I pass previously generated scenarios and policies instances to the perform_experiments method and assign them a name (let's say 'experiments').
* I print (as a pandas dataframe) the 'scenarios' instance. The indeces of this dataframe run from 0 to 49 (50 scenarios as expected).
* I print (as a pandas dataframe) the 'policies' instance. The indeces of this dataframe run from 0 to 4 (5 policies as expected).
* I print (as a pandas dataframe) the 'experiments' instance. Here is the mismatch. The 'scenario' column runs from 50 to 99 and the 'policy' column runs from 5 to 9. I am assuming that the perform_experiments method does not reset the indeces/references and just starts from the latest index (although the scenarios and policies instances are the same in both cases).

I was wondering if there is any practical solution to solve this issue (other than using direclty the number of scenarios and policies within the perform_experiments method). Or maybe you can point me towards a similar issue and how they solved it. Many thanks.

**Comment by quaquel** [comment]
Can you share a simple example of your code preferably with a model from the examples folder?

**Comment by omarcastrejon** [comment]
I tried to replicate the idea using the simple lake model, however the outcome was okay when I ran it using a pure python file (.py) and PyCharm as the IDE. Thus, I have attached the code I am running using jupyter notebook, and vensim  (please see Out[9], Out[11], and Out[18]). Maybe the problem is when using multiprocessing within jupyter notebook (on a Windows machine). 
[EMA_analysis_example.pdf](https://github.com/quaquel/EMAworkbench/files/7595136/EMA_analysis_example.pdf)

**Comment by quaquel** [comment]
Using multiprocessing within a notebook is a bad idea unless you are on Linux. I generally use .py files to generate my data and use notebooks only for the analysis.
