### ISSUE TITLE
SimioDLL File Not Found - while importing connectors

### ISSUE THREAD

**Issue by TwandN** [quaquel/EMAworkbench#115]
Running the lines below:

![image](https://user-images.githubusercontent.com/84083319/165114011-e89796d5-719e-4a0a-a7f6-d79d44d8d375.png)

Results in the following error message:

![image](https://user-images.githubusercontent.com/84083319/165112844-6603bff9-f928-408b-9d5a-64c6db7dc78a.png)

Installing simio does not seem to resolve the issue.

**Comment by quaquel** [comment]
fixed in 2.1.2
