### ISSUE TITLE
Pandas append() method depreciated, replace all occurrences with concat()

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#126]
Using [`DataFrame.append()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html) is depreciated with Pandas 1.4. All occurrences should be replaced with [`pandas.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat) to ensure compatibility with future Pandas version.

See https://github.com/pandas-dev/pandas/issues/35407 for their motivation why they depreciated it.

**Comment by EwoutH** [comment]
If you search in a recent CI run on `depr` or `.append` you will find some. The difficult thing is that `.append()` also a method is for other classes.

I tried to use PyCharm to automatically find instances of `DataFrame.append()`, but couldn't figure out how.

If you take [this run](https://github.com/EwoutH/EMAworkbench/runs/6492984748?check_suite_focus=true) for example, there is [one](https://github.com/EwoutH/EMAworkbench/runs/6492984748?check_suite_focus=true#step:6:167) in:
https://github.com/quaquel/EMAworkbench/blob/14488d76a0e45f8a6177e0508b7f1044db150dac/ema_workbench/analysis/feature_scoring.py#L389
and [one](https://github.com/EwoutH/EMAworkbench/runs/6492984748?check_suite_focus=true#step:6:177) in
https://github.com/quaquel/EMAworkbench/blob/3d1622360fce314add559ed5d61a33bc40b859bd/ema_workbench/analysis/logistic_regression.py#L253
These might be the only ones, there might be more.

**Comment by EwoutH** [comment]
I think all cases are gone, so this issue can be closed. Thanks!

**Comment by quaquel** [comment]
great, thanks for checking.
