### ISSUE TITLE
`max_features="auto"` depreciated in RandomForestClassifier used in feature_scoring.py

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#127]
The usage of `max_features="auto"` as parameter value in [RandomForestRegressors](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) and [ExtraTreesRegressors](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html#sklearn.ensemble.ExtraTreesClassifier) is depreciated in scikit-learn 1.1 and will be removed in 1.3. The default value for `max_features` also changed from from `"auto"` to `"sqrt"` in version 1.1.

In _analysis/feature_scoring.py_ this function is used:

https://github.com/quaquel/EMAworkbench/blob/c1da7cf93a56ef3fd3fc0f24b1139f392cef288a/ema_workbench/analysis/feature_scoring.py#L159-L164

The full [warning](https://github.com/quaquel/EMAworkbench/runs/6452924618?check_suite_focus=true#step:6:32) from the CI:

> test_get_rf_feature_scores (test.test_analysis.test_feature_scoring.FeatureScoringTestCase) ... /opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.

See https://github.com/scikit-learn/scikit-learn/issues/20111 for the motivation and discussion behind the depreciation.

@quaquel What new value is most appropriate?

**Comment by quaquel** [comment]
just change it to `sqrt` seems the obvious fix

**Comment by EwoutH** [comment]
> Just change it to `sqrt` seems the obvious fix

Great, seemed indeed obvious but wanted to confirm since (at this moment) I have no idea how important such a value is for the algorithm.

Changed it in https://github.com/quaquel/EMAworkbench/pull/129.
