### ISSUE TITLE
Netlogo 6 on Linux

### ISSUE THREAD

**Issue by floristevito** [quaquel/EMAworkbench#143]
Upon helping another student on setting up his Netlogo 6.2.2 model on a Linux (Red Hat) server, and double-checking the issues on my own machine (Ubuntu 22), I stumbled across some small issues. 

 1. Instantiating a NetLogoModel with the required `netlogo_version` argument equal to '6' resulted in a keyerror. Omitting this argument entirely fixed this issue.
 2. When setting up the runs on a new machine, some unexpected java related problems seemed to occur when performing a model run. Eventually, this could be solved by passing the jvm_home argument with the absolute path needed. 

Maybe these points are already known, in that case this issue can be disregarded. But I could not find much information about it, so I wanted to double-check.

**Comment by quaquel** [comment]
Are these issues to be addressed in the workbench, or in pynetlogo? both kwargs are to my knowledge passed on to pynetlogo?

**Comment by floristevito** [comment]
You are

**Comment by floristevito** [comment]
You are absolutely right, both are directly passed to Pynetlogo I see. Furthermore, I discovered that providing version argument '6.2' did work correctly. So no issues in the code itself, and this can be closed. The remarks are only related to passing the right argument on Linux. 

Thank you for the quick reply!
