### ISSUE TITLE
Scenario Discovery results interpretation

### ISSUE THREAD

**Issue by saeedashraf** [quaquel/EMAworkbench#153]
Hey
I'm wondering what do the numbers in the following syntax of scenario discovery mean? and how we can interpret different results by changing the numbers?

For instance here is the first attempt: 
![image](https://user-images.githubusercontent.com/22497185/177356897-41e5c140-fd8c-4da4-862c-b3c88f32fb2a.png)

the second attempt: 
![image](https://user-images.githubusercontent.com/22497185/177357623-10826d0f-37a1-4289-83a8-82788ba5621a.png)

**Comment by quaquel** [comment]
Your question is not entirely clear, but my hunch is that you are asking after the meaning of `20` and `30`?

**Comment by quaquel** [comment]
I suggest you first read the original paper by Ben Bryant and Rob Lempert from 2010 on Scenario Discovery. This explains a lot of the terminology that is still used today. These numbers refer to points along the peeling and pasting trajectory. So 20 is the 20th step / box and 30 means the 30th step / box on this trajectory.

**Comment by saeedashraf** [comment]
ok Thanks
https://www.sciencedirect.com/science/article/pii/S004016250900105X

**Comment by quaquel** [comment]
yes that is the correct paper.
