### ISSUE TITLE
Create overview/docs of examples

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#157]
Currently there is no overview of which example show what. This could be in a readme.md and/or readthedocs page.

https://github.com/quaquel/EMAworkbench/tree/master/ema_workbench/examples

**Comment by EwoutH** [comment]
This will be a main project for 2.4.0.

**Comment by quaquel** [comment]
Started thinking about this. It is relatively easy to autogenerate an examples page in the documentation with links to each example. 

In conf.py, or a separate new .py file called from conf.py, you loop over all the .py files in the examples folder. For each file, you auocreate an .rst file with the [literalinclude](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude) directive. 

In a seperate examples.rst, you add a list with a [toctree](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree) with all the autogenerated rst files. This is most easily done by creating the basic examples.rst, but from the new .py file overwrite the toctree part with the list of examples.

does this make sense?

The only minor drawback is that there is no easy way to add further structure to the toctre (e.g., organize examples by functionality they showcase).

**Comment by quaquel** [comment]
Have a first attempt up and running as part of https://github.com/quaquel/EMAworkbench/tree/examples_docs. Added it to readthedocs as well so docs should be available for viewing within a few minutes. The docs worked locally.

**Comment by EwoutH** [comment]
Nice, this is a great first step!

**Comment by quaquel** [comment]
Closed with #244
