### ISSUE TITLE
Enable Read the Docs for Pull Requests

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#171]
For reviewing pull-requests, it would be usefull if Read the Docs are generated for each pull-request. This is supported, see https://docs.readthedocs.io/en/stable/pull-requests.html.

@quaquel Could you enable this in the Admin settings of Read the Docs?

**Comment by quaquel** [comment]
I have enabled it

**Comment by quaquel** [comment]
I noticed that the new toml file breaks read the docs. This is because the current setup of read the docs relied on the requirements file. My hunch is that it is just a matter of updating the configuration on read the docs.

**Comment by EwoutH** [comment]
Good catch! I will look into it tomorrow, having Read the Docs configured with a YAML file tracked in Git is a good idea anyways anyways.

**Comment by quaquel** [comment]
I tried adding you, but it seems you need a readthedocs account.

I have also modified a few things for triggering on pull requests within the GitHub webhook because it still was not working.

**Comment by EwoutH** [comment]
Thanks!
