### ISSUE TITLE
CI: Add Black code formatting (using pre-commit)

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#177]
While Flake8 formatting is currently [checked](https://github.com/quaquel/EMAworkbench/blob/abfaafb3966a7464a6553a49eef25e0852b1f7bf/.github/workflows/ci.yml#L50-L63) in the CI, Black is not, leading to quite come clean-up commits. Adding [Black](https://github.com/psf/black) formatting to the CI using a [pre-commit](https://pre-commit.com/) hook/workflow could detect and potentially even directly fix those.

Also [pyupgrade](https://github.com/asottile/pyupgrade) might be a useful hook to run.

**Comment by quaquel** [comment]
yes to both. Would be great to have this automatically taken care off.

**Comment by EwoutH** [comment]
@quaquel Could you enable Pre Commit for this repository on https://pre-commit.ci/ ?

**Comment by quaquel** [comment]
It should now be enabled.

do we want to add the batch to the readme.md?

**Comment by EwoutH** [comment]
Awesome, and yes we should document it somewhere, maybe [CONTRIBUTING.md](https://github.com/quaquel/EMAworkbench/blob/master/CONTRIBUTING.md).

**Comment by EwoutH** [comment]
Formatted in #178 and added to CI in #181!

**Comment by quaquel** [comment]
Thanks!
