### ISSUE TITLE
Link to documentation in readme redirects to image

### ISSUE THREAD

**Issue by ConnectedSystems** [quaquel/EMAworkbench#22]
As in title, the link to the documentation does not work. It instead displays the documentation version badge image. Copy pasting the link without the `badge/?version=latest` works, but I think it goes to the wrong page.

The correct link is: http://emaworkbench.readthedocs.io/en/latest/
Current link redirects to: https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat

**Comment by quaquel** [comment]
should be fixed
