### ISSUE TITLE
Import Error: epsilon_nondominated 

### ISSUE THREAD

**Issue by SnuggleBug91** [quaquel/EMAworkbench#223]
In the section on directed search the following import doesn't work. 

'''
from ema_workbench.em_framework.optimization import epsilon_nondominated
'''

This is my first time writting an issue so not sure if you need any more than this.

**Comment by quaquel** [comment]
Thanks for reporting this issue. You have to be a bit more specific than this. I don't know what you mean with "the section on  directed search". It would also help if you can indicate what version of the workbench you are using (`print(ema_workbench.__version__)`).

**Comment by SnuggleBug91** [comment]
Sorry, I wasn't particularly helpful with my comment. Apologies.

The error comes from following the tutorial on the ema workbench website: [https://emaworkbench.readthedocs.io/en/latest/indepth_tutorial/directed-search.html](url)

Specifically, when combing multiple runs of optimising by searching over levers then combining the non-dominated solutions into one dataset. 

The code block in question is 
`from ema_workbench.em_framework.optimization import epsilon_nondominated, to_problem

problem = to_problem(model, searchover="levers")
epsilons = [0.05] * len(model.outcomes)
merged_archives = epsilon_nondominated(results, epsilons, problem)`

The version of the workbench I'm running is 2.2.1

**Comment by EwoutH** [comment]
@SnuggleBug91 Could you update to 2.3.0 and see if the bug still persist? I'm not sure, but it might be fixed already in https://github.com/quaquel/EMAworkbench/pull/150.

**Comment by omarcastrejon** [comment]
Hi,
Have you found a solution to this issue?
I am having the same problem trying to use _epsilon_nondominated_. I am using version 2.4.0 of the EMA workbench. Not sure what the problem could be but this is the error I get:
![image](https://github.com/quaquel/EMAworkbench/assets/94148091/44fc841d-0080-42cf-a155-370cb342cd52)
Any thoughts?
Thank you in advance.

**Comment by quaquel** [comment]
There is a fix on master, just need time to cherry-pick al bug fixes since last release to create a new release. You can still install master through pip (check google)

**Comment by omarcastrejon** [comment]
@quaquel  thank you for your quick reply. I have installed the master version (2.5.0.dev0) but unfortunately I'm still getting an AttributeError and and EMAError (please see below). Any advice would be really appreciated. Thank you.

![image](https://github.com/quaquel/EMAworkbench/assets/94148091/cfe68926-eecf-4064-9634-0501d7f10c33)

**Comment by omarcastrejon** [comment]
By looking at some documentation on _DataFrame.itertuples_, _itertuples()_ does not work with column names that include special characters such as spaces or '-'. My suggestion: either (1) create a note saying that the name of the levers should not include special characters; or (2) use _named itertuples()_ by creating a temporary list of names to iterate over DataFrame rows as namedtuples.

**Comment by quaquel** [comment]
There is already an open issue for this (#274)
