### ISSUE TITLE
Altair missing as dependency

### ISSUE THREAD

**Issue by quaquel** [quaquel/EMAworkbench#225]
Altair is used by PRIM, but currently not installed as part of the recommended packages.

**Comment by EwoutH** [comment]
It should be installed when installing `ema_workbench[recommended]`. Recommend includes graph, and graph includes altair.

https://github.com/quaquel/EMAworkbench/blob/5628cc19a8e9a98da8ae3b8faece7280a2028cb0/pyproject.toml#L32-L41

**Comment by quaquel** [comment]
Thanks, I overlooked that. Was doing some tests on Colab and notices altair was not installing. But that is because altair comes pre-installed most likely with colab.
