### ISSUE TITLE
GitHub actions stalling on Ubuntu?

### ISSUE THREAD

**Issue by quaquel** [quaquel/EMAworkbench#226]
The test actions on Ubuntu with python 3.8, 3.9, and 3.10 seem to be timing out after 6 hours. A first check suggest they time out on the logit test.

**Comment by EwoutH** [comment]
I think this has to do with NumPy-Pandas interaction since the NumPy 1.24 release (see https://github.com/quaquel/EMAworkbench/pull/217#issuecomment-1356885941). Couldn't figure it out further.

**Comment by EwoutH** [comment]
Ubuntu jobs are now only failing some times:
- https://github.com/quaquel/EMAworkbench/actions/runs/4351663280
- https://github.com/quaquel/EMAworkbench/actions/runs/4364875098
- https://github.com/quaquel/EMAworkbench/actions/runs/4364880722

**Comment by EwoutH** [comment]
It looks like pytest sometimes gets stuk on
```
test/test_analysis/test_logistic_regression.py::LogitTestCase::test_logit PASSED [ 14%]
```
When it passes, this test gives the following RuntimeWarning
```
test/test_analysis/test_logistic_regression.py::LogitTestCase::test_logit
  /home/runner/work/EMAworkbench/EMAworkbench/ema_workbench/analysis/logistic_regression.py:66: RuntimeWarning: invalid value encountered in scalar divide
    precision = tp / (tp + fp)
```
Could it be that in this test the possible values are sometimes 0, thereby dividing by 0?

If might be far fetched that it crashes on this, but we probably should fix it anyway.

**Comment by quaquel** [comment]
I hope to have a chance to run some tests in the coming days to see if I can isolate the problem. As part of that, I will look into this and address this as well.

**Comment by EwoutH** [comment]
I tested some things about the `test_logit` hangs. It looks like it isn't the interactive plotting or the division by 0 when calculating precision and recall.

**Comment by quaquel** [comment]
Ran some tests myself. It hangs on [`model.fit()`](https://github.com/quaquel/EMAworkbench/blob/6678c42b43bd3a3be4069c24b2bcc47eda6e2362/ema_workbench/analysis/logistic_regression.py#L214). If I change this by passing `method="newton", maxiter=2`, it runs fine. See https://github.com/quaquel/EMAworkbench/actions/runs/4610674367. 

So an obvious solution will be to add a modelfit_kwargs to `Logit.run()`, and use this to control the test code, it seems fixable. It does not, however, explain why the code is stalling.
