### ISSUE TITLE
Pairs plotting dependent on load_results

### ISSUE THREAD

**Issue by steipatr** [quaquel/EMAworkbench#236]
`plot_pair_wise_scatter` only works properly with categorical parameters if the data has been imported with `load_results`, if the data was generated directly with `perform_experiments`, you run into some dtype issues. This is because there is a type conversion in `load_results`  https://github.com/quaquel/EMAworkbench/blob/5628cc19a8e9a98da8ae3b8faece7280a2028cb0/ema_workbench/util/utilities.py#L68 that is expected/necessary for correctly drawing boxes in `plot_pair_wise_scatter`.

In a normal EMA workflow, this probably isn't an issue, since normally you would save/load data before analysing it, but when debugging improved plotting functions, it can be a problem :)

Raising this issue for awareness. I know in the TODO there is something mentioned about moving from the whole category business to Enum or NamedTuple, so maybe this can be taken along there.

**Comment by quaquel** [comment]
Would be good to address this as part of #232
