### ISSUE TITLE
EMA cannot find pyNetLogo module - name change issue?

### ISSUE THREAD

**Issue by steipatr** [quaquel/EMAworkbench#245]
Trying to run EMA+NetLogo with newest package versions gives error "ModuleNotFoundError: No module named 'pyNetLogo'". Based on https://github.com/steipatr/aul/issues/2, this might be because of the name change from pyNetLogo to pynetlogo? I found two places in the EMA code where the old name is used:

https://github.com/quaquel/EMAworkbench/blob/6c1b55c3f7d352d7239a373b450a66ce40b69ca8/ema_workbench/connectors/netlogo.py#L14

https://github.com/quaquel/EMAworkbench/blob/6678c42b43bd3a3be4069c24b2bcc47eda6e2362/ema_workbench/connectors/netlogo.py#L28

**Comment by steipatr** [comment]
Manually updating the package name in the two aforementioned lines of code (plus https://github.com/quaquel/EMAworkbench/blob/6678c42b43bd3a3be4069c24b2bcc47eda6e2362/ema_workbench/connectors/netlogo.py#L138 which I somehow missed the first time around) does indeed fix the described issue. Now working through some weird `netlogo_version` errors, will update here.

**Comment by steipatr** [comment]
There are some mismatches between what EMA is passing to pynetlogo, and what pynetlogo is expecting. Trying to track down the issues here to the best of my ability. 

EMA passes (https://github.com/quaquel/EMAworkbench/ema_workbench/connectors/netlogo.py#L138):

```
self.netlogo = pyNetLogo.NetLogoLink(
      netlogo_home=self.netlogo_home,
      netlogo_version=self.netlogo_version,
      jvm_home=self.jvm_home,
      gui=self.gui,
      jvmargs=self.jvmargs,
  )
```

pynetlogo expects (https://github.com/quaquel/pyNetLogo/blob/master/src/pynetlogo/core.py#L173):

```
def __init__(
    self,
    gui=False,
    thd=False,
    netlogo_home=None,
    jvm_path=None,
    jvmargs=[],
):
```

So you get some unexpected kwarg errors related to `jvm_home` and `netlogo_version`. I "solved" both issues manually by substituting and commenting out as necessary.

**Comment by quaquel** [comment]
Can you check https://github.com/quaquel/EMAworkbench/compare/master...pynetlogo to make sure I covered everything?

**Comment by steipatr** [comment]
Minor typo in L28 (pynet**L**ogo): https://github.com/quaquel/EMAworkbench/commit/81fa67c50bf0fa8384267ff0538bb9814a0c479f#diff-2b2d89f57fef051c3f21300543758985587efc668ecdffa852ec5315b7039145R28

Otherwise it works on my end (up to the point where I get a Java version error, but that's on the WUR, not EMA/pynetlogo).
