### ISSUE TITLE
check if uncertainties/levers are defined if sampling them

### ISSUE THREAD

**Issue by quaquel** [quaquel/EMAworkbench#281]
When performing experiments and passing a number for scenarios or policies, check to see if any uncertainties or levers are defined and throw an informative exception otherwise. Addresses a point raised in the discussion (#271).

**Comment by EwoutH** [comment]
With https://github.com/quaquel/EMAworkbench/pull/282 merged, is this issue resolved, or would you like to make additional enhancements?
