### ISSUE TITLE
`test_plot_cdfs` test is extremely slow

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#298]
This test takes extremely long, in the order of minutes. I wouldn't be surprised if it's over half of all testing time.

https://github.com/quaquel/EMAworkbench/blob/b76b487afc5fbaaa34e5a055269657ff15fa908e/test/test_analysis/test_regional_sa.py#L14-L23

**Comment by EwoutH** [comment]
Performance profile:

![Screenshot_201](https://github.com/quaquel/EMAworkbench/assets/15776622/8be35b54-172b-4c2e-9a28-4a4ebc58839a)
![Screenshot_202](https://github.com/quaquel/EMAworkbench/assets/15776622/4a3ac6d3-b99c-4f42-a1f7-e3b4fbc6e3e9)

Looks like matplotlib's [`autoscale_view`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.autoscale_view.html) is called a lot of times, which seems to be the most expensive operation.

**Comment by quaquel** [comment]
No idea why autoscale_view is called so often. There are 63 calls to plot_individual_cdf, so that is close 400 calls to autoscale per cdf (this is not the only place where autoscale might be called, but likely the dominant one). It's also strange to autoscale because at least the x-axis has a clearly defined hard-coded limit. It seems this arises from somewhere deep within matplotlib.

**Comment by EwoutH** [comment]
Here the tree:

![EMAworkbench_plot_cdf_profile](https://github.com/quaquel/EMAworkbench/assets/15776622/9aba65a0-a5a8-4baa-94af-fc91ae965b34)

It seems that from `plot_discrete_cdf` (called 6 times) `inner` is the first function that's called that 24024 times, all the way to `autoscale_view`.

**Comment by quaquel** [comment]
The calls to scatter in `plot_discrete_cdf` might be redundant and could be replaced by using marker in the plot command. Would need some checking, however.

**Comment by quaquel** [comment]
Just ran a quick test. With scatter enabled timeit gives

`52 s ± 732 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

With scatter disabled, and replaced with the marker kwarg in plot we get

`621 ms ± 3.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

So, disabling scatter gives us orders of magnitude improvement, and no discernable difference in the visual.

**Comment by EwoutH** [comment]
That's 3 orders of magnitude, or a reduction of 99.9% of the runtime.

Are there any figures where the scatter is likely required to provide a correct/useful visual? If so we should test those.

**Comment by quaquel** [comment]
I did a visual comparison. It is really marginal.

**Comment by EwoutH** [comment]
Then the speedup sounds worth it!
