### ISSUE TITLE
Running a model for N replications but without iterating over uncertainties or levers

### ISSUE THREAD

**Issue by mikhailsirenko** [quaquel/EMAworkbench#319]
The current implementation of `ReplicatorModel` in combination with `perform_experiments` does not run, let's say 10 replications, without iterating over the parameters. Would it be a good idea to allow such a "Monte Carlo" setup?

**Comment by quaquel** [comment]
I don't know what you mean by saying that it does not run. I have frequently used `ReplicatorModel ` in conjunction with perform_experiments and it worked fine. The idea of `ReplicatorModel` is to run each ema experiment for _n_ replications.

So can you explain what you mean and ideally give a minimum example of what you are trying to work which is not working. .

**Comment by mikhailsirenko** [comment]
Apologies, I forgot to attach it. Perhaps that is quite a unique setup, and it slightly deviates from the "general idea" of the framework. Or maybe I just initialised it wrong. So, here is the setup—a stochastic model with a set of constants, no uncertainties or levers yet. Thus, the variability of the outcomes is defined by the seed only.

```
from ema_workbench import (ReplicatorModel, ScalarOutcome, Constant, perform_experiments)
import numpy as np

def some_model(x1=None, x2=None):
    x3 = np.random.randint(0, 10)
    return {'y' : x1 * x2 + x3}

model = ReplicatorModel('simpleModel', function=some_model)

model.constants = [Constant('x1', 2),
                   Constant('x2', 3)]
                   
model.outcomes = [ScalarOutcome('y')]

model.replications = 2

results = perform_experiments(model)
```

**Comment by quaquel** [comment]
Since you have no uncertainties or levers, there can be no experiments. This is thus desired behavior, although I would expect an exception to be thrown (or might this just be fixed on master that still needs to be released?)_

You might be able to get what you want by calling `run_model` on the model directly. You would need to pass a `Scenario` and `Policy` instance, but these can both just be empty.

**Comment by mikhailsirenko** [comment]
Yes, indeed, such a setup worked, thanks! It required changing the `ScalarOutcome` to `ArrayOutcome`, but that's it. I'm keeping a snippet here in case anyone would wonder about such a case.

```
from ema_workbench import (ReplicatorModel, ArrayOutcome, Constant, perform_experiments, Scenario, Policy)
import numpy as np

def some_model(x1=None, x2=None):
    x3 = np.random.randint(0, 10)
    return {'y' : x1 * x2 + x3}

model = ReplicatorModel('simpleModel', function=some_model)

model.constants = [Constant('x1', 2),
                   Constant('x2', 3)]
                   
model.outcomes = [ArrayOutcome('y')]

model.replications = 19
my_scenario = Scenario()
my_policy = Policy()
model.run_model(scenario=my_scenario, policy=my_policy)
```
