### ISSUE TITLE
'NoneType' object has no attribute 'Real'

### ISSUE THREAD

**Issue by yjx4131** [quaquel/EMAworkbench#32]
I get error messages when I implement "Directed search with the Exploratory Modeling workbench" following the documentation.  (https://emaworkbench.readthedocs.io/en/latest/indepth_tutorial/directed-search.html)

input:

from ema_workbench import (RealParameter, ScalarOutcome, Constant, Model)
from dps_lake_model import lake_model

model = Model('lakeproblem', function=lake_model)
.......
#________________________________________________________
from ema_workbench import MultiprocessingEvaluator
from ema_workbench import ema_logging

ema_logging.log_to_stderr(ema_logging.INFO)

with MultiprocessingEvaluator(model) as evaluator:
    results = evaluator.optimize(nfe=250, searchover='levers',
                                 epsilons=[0.1,]*len(model.outcomes),
                                 constraints=constraints)
#___________________________________________________________

Error message:
[MainProcess/INFO] pool started
[MainProcess/INFO] terminating pool
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-117-d0ee47af1882> in <module>()
      8     results = evaluator.optimize(nfe=250, searchover='levers',
      9                                  epsilons=[0.1,]*len(model.outcomes),
---> 10                                  constraints=constraints)

C:\Anaconda3\lib\site-packages\ema_workbench\em_framework\evaluators.py in optimize(self, algorithm, nfe, searchover, reference, constraints, **kwargs)
    179         return optimize(self._msis, algorithm=algorithm, nfe=int(nfe),
    180                         searchover=searchover, evaluator=self,
--> 181                         reference=reference, constraints=constraints, **kwargs)
    182 
    183     def robust_optimize(self, robustness_functions, scenarios,

C:\Anaconda3\lib\site-packages\ema_workbench\em_framework\evaluators.py in optimize(models, algorithm, nfe, searchover, evaluator, reference, convergence, constraints, **kwargs)
    503 
    504     problem = to_problem(models, searchover, constraints=constraints,
--> 505                          reference=reference)
    506 
    507     # solve the optimization problem

C:\Anaconda3\lib\site-packages\ema_workbench\em_framework\optimization.py in to_problem(model, searchover, reference, constraints)
    119 
    120     '''
--> 121     _type_mapping = {RealParameter: platypus.Real,
    122                      IntegerParameter: platypus.Integer,
    123                      CategoricalParameter: platypus.Permutation}

AttributeError: 'NoneType' object has no attribute 'Real'

**Comment by quaquel** [comment]
did you install the platypus optimisation package (https://github.com/Project-Platypus/Platypus)?

**Comment by yjx4131** [comment]
Yes, I installed and imported it.
And, I tried this model just now, this time it works well for. I don't know why. It is strange!
Anyway, thank for all your work on this wonderful workbench.
Best wishes.
