### ISSUE TITLE
Error in show_pairs_scatter for PRIM output with CategoricalParameter

### ISSUE THREAD

**Issue by jpn--** [quaquel/EMAworkbench#33]
A `TypeError: unhashable type: 'set'` exception is raised when running the method `ema_workbench.analysis.prim.PrimBox.show_pairs_scatter` when one of the restricted dimensions is categorical.

Running Python 3.6, the error is reproducible on macOS and Windows.

Example:
https://gist.github.com/jpn--/aa6dee82e6c567da952a9ac736a5393f

**Comment by quaquel** [comment]
Fixed in the V2 Branch.
