### ISSUE TITLE
Cannot use analysis tools: Feature Scoring

### ISSUE THREAD

**Issue by brodderickrodriguez** [quaquel/EMAworkbench#36]
I am running a Netlogo model through EMA Workbench and I am able to output a correct 3d array. However, Feature Scoring requires a 2d array. See error below:

`File ".../venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 565, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.`

Using a (very) slightly modified version of your example from the documentation, this is what I am attempting to run: 

    from ema_workbench.analysis import feature_scoring
    import matplotlib.pyplot as plt
    import seaborn as sns

    experiments, outcomes = results_output
    fs = feature_scoring.get_feature_scores_all(experiments, outcomes)
    sns.heatmap(fs, cmap='viridis', annot=True)
    plt.show()

I am running into a similar issue when trying to use Prim or Dimensional Stacking. Do you have a solution for this? am I running the model incorrectly?

I have forked your project. For my exact implementation please see [this file](https://github.com/brodderickrodriguez/EMAworkbench/blob/master/ema_workbench/examples/netlogo_plume.py).

**Comment by quaquel** [comment]
what is the shape of each outcome array? Feature scoring, CART, PRIM, and dimensional stacking all work on on 1D arrays (shape = (n_experiments, 1)). So if you produce time series, you will have to specify the point in time for which you want to run it. See e.g. prim_flu_example.py, where we slice the outcome to get the final value 

```python
outcome = outcomes['casualties']
endstate = outcome[:, -1] # gets the final value
```

If you want to do this for with `get_feature_scores_all` you would do something like

```python
end states = {k:v[:,-1] for k,v in outcomes.items()}
fs = feature_scoring.get_feature_scores_all(experiments, end states)
```
