### ISSUE TITLE
Vensim connector

### ISSUE THREAD

**Issue by sibeleker** [quaquel/EMAworkbench#41]
I am trying to run a Vensim model using the multiprocessing evaluator. The model reads data from an excel file. It causes an error in run_model, traced back to an "OSError: exception: access violation reading 0x00000000". This is because of trying to read from Excel files with the same name in the cloned directories. I have no problem opening/reading only excel files with the same name in multiprocessing. I think, the problem is about Vensim/Excel connection. However, Vensim people say that the normal Vensim DLL cannot be used for multi-processing, which is obviously not true. Any idea about the cause of this problem?

**Comment by quaquel** [comment]
I have used excel with vensim and multiprocessing successfully in the past. So I know it can work. 

A few questions:
- which version of windows?
- which version of vensim?
- what is the directory structure?

Have you tried moving the excel file out of the directory in which the vensim file resides? That is, don't have multiple copies of the excel file. In principle is only writing to file a problem in multiprocessing. Reading from is no problem.

Alternatively, would it be possible to read the excel files in Python and use them as constants?

**Comment by sibeleker** [comment]
Thanks!

I use Windows 10 64bit and Vensim 7.3 32bit.

Both the model file and the excel file are in the same directory, say 'C:/Users/eker/Documents/Felix_runs/', and this is the working directory used in multiprocessing.

I can try keeping the Excel file out, but I think it must be in the same directory as the model file, because the model reads from the Excel file using predefined Vensim functions, which require them to be in the same directory. 

Yes, I think the alternative solution you suggested would work. I am just trying to avoid it :)

**Comment by quaquel** [comment]
I am not an active Vensim user myself so I have no idea, but are you certain that vensim requires that the excel file is in the same directory?

**Comment by sibeleker** [comment]
I was sure but apparently I shouldn't have been. It worked fine when I took the Excel file out of the directory. Thanks a lot!
