### ISSUE TITLE
Issue with Python 3.7

### ISSUE THREAD

**Issue by jorenvanlindert** [quaquel/EMAworkbench#42]
When initializing a MultiprocessingEvaluator instance an error occurs:

```
in initialize
    self._pool._taskqueue.maxsize = self._pool._processes * 5
AttributeError: '_queue.SimpleQueue' object has no attribute 'maxsize'
```
Caused by the change from queue.Queue() to queue.SimpleQueue() in the multiprocessing package: python/cpython#5216

**Comment by quaquel** [comment]
This has now been fixed in the V2 branch. I aim to back port the fix to master and update pypi

**Comment by quaquel** [comment]
pypi has been updated to fix this issue
