### ISSUE TITLE
wondering about how to difine constraints in directed search.

### ISSUE THREAD

**Issue by yjx4131** [quaquel/EMAworkbench#51]
I have read through the docs and got little information about how to specify constraints in a constrained optimization problem.

The only explanations about specifying constraints in the manual are that "A constraint can be applied to the model input parameters (both uncertainties and levers), and outcomes. A constraint is essentially a function that should return the distance from the feasibility threshold. The distance should be 0 if the constraint is met."

An example was illustrated as follow in the lake pollution problem.
constraints = [Constraint("max pollution", outcome_names="max_P", function=lambda x:max(0, x-1))]

My understanding of this constraint is that the "max_P" objective should be smaller than (or equal to) 1? 
I did not find any information about the Constraint class both in the docs and the GitHub library, so I guess that the `outcome_names="max_P"` parameter tells the optimization algorithm that this constraint is applied to the objective (outcome) of "max_P"? Therefore, if I want to define constraints on uncertainties or levers, the corresponding parameters should be `uncertainty_names="an Uncertainty name" or lever_names="a Lever name"`?
As to the `function` parameter, if I want to define a constraint as `a <= x <= b`, how should I write the function parameter? Also, how should I define equality constraints like `sum(wj) = 1` as required by the lake model? Another question is that is it possible to utilize a user-defined function instead of a lambda expression to define the constraints (`function="user-defined function"`)?
And multiple constraints should be defined as follow?
constraints = [Constraint(...), Constraint(...),Constraint(...),...]

Thanks very much if you can give some instructions!!!
Best regards,
Jyang

**Comment by quaquel** [comment]
The documentation on constraints can definitely be improved. 

If a constraint applies to one or more outcomes, `outcome_names` should be a string or list of strings. The strings should match the name of one of the outcomes defined as part of `model.outcomes`.

**Comment by yjx4131** [comment]
Thanks very much, really appreciate your explanation and one more question.

If I want to define the following constraints: `a < max_P < b, c < utility, b < 1.5, and 0 < w1 < 1`, 
the distances from the threshold of these outcomes or uncertainties and levers should be calculated as follows?
For `max_P`: `max(0, a-x, x-b)`
For `utility`: `max(0, c-x)`
For `b` and `w1`: `max(0, x-1.5)`, and `max(0, 0-x, x-1)`

And the syntax to define the constraints in EMA should be: constraints = [Constraint("multi Constraints", outcome_names=["max_P", "utility"], parameter_names = ['b', 'w1'], function=my_function)]

The defination of the function callable (my_function) may be something as follow?
How shoud the distances corresponding to each outcome or parameter be returned, in a tuple or dict?
```
def my_function(*var):
    '''
    "var" is treated as a tuple consist of (max_P, utility, b, w1)
    '''
    # calculate the distance from the feasibility threshold of "max_P"
    dis_max_P = max(0, a-var[0], var[0]-b)
    # calculate the distance from the feasibility threshold of "utility"
    dis_utility = max(0, c-var[1])
    # calculate the distance from the feasibility threshold of "b"
    dis_b = max(0, var[2]-1.5)
    # calculate the distance from the feasibility threshold of "w1"
    dis_w1 = max(0, 0-var[3], var[3]-1)`

    return dis_max_P, dis_utility, dis_b, dis_w1
```

Above are my understandings of constraints after I went through the definations of the Constraint class in the repo and read your explanations.

**Comment by quaquel** [comment]
This won't work. A constraint should return a single number not a tuple. Either take the max over the different constraints, or probably clearer do

```python
model.constraints = [Constraint("c1", outcome_names="max_utility", function=func1),
                     Constraint("c2", outcome_names='utility", function=func2),
                     #etc.]
```
since your constraint are one line, you could choose to use lambda expressions

**Comment by yjx4131** [comment]
Thanks, I will try it.
