### ISSUE TITLE
How to log to stdout instead stderr?

### ISSUE THREAD

**Issue by stefaneidelloth** [quaquel/EMAworkbench#53]
I am new to ema workbench and try to use it with Eclipse PyDev. When I log the progress I get red error output in the console. 

I would like to use 

` ema_logging.log_to_stdout(ema_logging.INFO)`

instead of

` ema_logging.log_to_stderr(ema_logging.INFO)`

However, there is not such a method. 

=>How can I log progress to stdout instead of stderr?

![image](https://user-images.githubusercontent.com/12675339/55147410-9fad3500-5146-11e9-822d-3d178968b0c1.png)

**Comment by stefaneidelloth** [comment]
Related issue: https://stackoverflow.com/questions/55394336/how-to-resolve-importwarning-cant-resolve-package-from-spec-in-eclip

**Comment by quaquel** [comment]
Your first question is a general logging question. It has nothing to do with the workbench or with pydev.

See e.g.: https://stackoverflow.com/questions/14058453/making-python-loggers-output-all-messages-to-stdout-in-addition-to-log-file for suggestions.

The related issue is something not related at all to logging, but a weird import issue. It has to do with changes in the python import system. As an eclipse user my self, I would love to see it resolved, but again it it not related to the workbench per se.

**Comment by stefaneidelloth** [comment]
Thank you for the fast reply. I am not yet familar with python logging. Do you suggest that ema workbench still logs to stderr but that all python output of stderr is redirected to stdout? 

If I replace

`ema_logging.log_to_stdout(ema_logging.INFO)`

with

   ```
 import sys
    import logging  
    root = logging.getLogger()
    root.setLevel(logging.DEBUG)    
    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    root.addHandler(handler)
```

I do not get the progress output.

If I leave the line in front of the logging config, the output is still red.

**Comment by quaquel** [comment]
log_to_sterr looks like this

```python

def log_to_stderr(level=None):
    '''
    Turn on logging and add a handler which prints to stderr

    Parameters
    ----------
    level : int
            minimum level of the messages that will be logged

    '''

    if not level:
        level = DEFAULT_LEVEL

    logger = get_rootlogger()

    # avoid creation of multiple stream handlers for logging to console
    for entry in logger.handlers:
        if (isinstance(entry, logging.StreamHandler)) and\
           (entry.formatter._fmt == LOG_FORMAT):
            return logger

    formatter = logging.Formatter(LOG_FORMAT)
    handler = logging.StreamHandler()
    handler.setLevel(level)
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.propagate = False

    return logger
```
the only change would be to change

```python
handler = logging.StreamHandler() 
```


to 

```python
handler = logging.StreamHandler(sys.stdout)
```

you would also need to import `get_rootlogger` from ema_logging

**Comment by stefaneidelloth** [comment]
Thank you. I locally adapted the source code of ema_logging to include an additional method and it works now.  Maybe you want to include that on Github, too.

For the warning issue I'm going to update the SO question. 

```
import sys
def log_to_stdout(level=None):
    '''
    Turn on logging and add a handler which prints to stderr

    Parameters
    ----------
    level : int
            minimum level of the messages that will be logged

    '''

    if not level:
        level = DEFAULT_LEVEL

    logger = get_logger()

    # avoid creation of multiple stream handlers for logging to console
    for entry in logger.handlers:
        if (isinstance(entry, logging.StreamHandler)) and\
           (entry.formatter._fmt == LOG_FORMAT):
            return logger

    formatter = logging.Formatter(LOG_FORMAT)
    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(level)
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.propagate = False

    return logger
```
