### ISSUE TITLE
Please add link to api doc for perform_experiments

### ISSUE THREAD

**Issue by stefaneidelloth** [quaquel/EMAworkbench#54]
In the python tutorial it says
>The function perform_experiments() takes the model we just specified and will execute 100 experiments. By default, these experiments are generated using a Latin Hypercube sampling, but Monte Carlo sampling and Full factorial sampling are also readily available. Read the documentation for perform_experiments() for more details.

But where to find that documentation? If I search the doc for "perform_experiments" I get some results but not the actual doc for perform_experiments.
=>Please add a direct link to the corresponding doc in the tutorial.

**Comment by stefaneidelloth** [comment]
Now found it under evaluators
https://emaworkbench.readthedocs.io/en/latest/ema_documentation/em_framework/evaluators.html

**Comment by stefaneidelloth** [comment]
Hi, you stated
>I am close to releasing a major update where the experiments are stored in a pandas dataframe
=>Could you please give an estimate when the structure of the results will be changed? Will that correspond to version 3.0 on pypi?

**Comment by quaquel** [comment]
I released this on pip 2 weeks ago, it is part of the V2 version of the workbench.

**Comment by stefaneidelloth** [comment]
Ok. Then only the doc needs some update. It still states that the experiments are a numpy recarray

>Returns: | the experiments as a numpy recarray,
https://emaworkbench.readthedocs.io/en/latest/ema_documentation/em_framework/evaluators.html

**Comment by quaquel** [comment]
yes, thanks for noticing it. 

Accidentally, I noticed this one myself yesterday while working on the 2.1 branch. I have fixed it there already but will fix it in 2.0 as well.
