### ISSUE TITLE
Not able to open model.vmp with Vensim DLL 6.0b

### ISSUE THREAD

**Issue by stefaneidelloth** [quaquel/EMAworkbench#55]
I tried to open the model.vpm file from the included vensim example and get following error:

![image](https://user-images.githubusercontent.com/12675339/55166551-9e443280-516f-11e9-942e-e20b6cbb97f2.png)

Do I need a distinct version of Vensim to work with the connector?

**Comment by quaquel** [comment]
you need the dss version of vensim, since only this version comes with the DLL. Also, you need to have python 32 bit.

**Comment by stefaneidelloth** [comment]
Issue seems that I have several versions of Vensim installed in parallel. After uninstalling Vensim PLE, that error message is not shown any more but different ones:
* "."
* "Reinstall Vensim (error 977)

Reinstalling Vensim and a restart did not help. The console shows

[EMA/INFO/MainProcess] performing 100 scenarios * 1 policies * 1 model(s) = 100 experiments
[EMA/INFO/MainProcess] performing experiments sequentially
[EMA/ERROR/MainProcess] float division by zero
Traceback (most recent call last):
  File "D:\EclipsePython\App\WinPython_3_7_2_0_32bit\python-3.7.2\lib\site-packages\ema_workbench\em_framework\experiment_runner.py", line 89, in run_experiment
    model.run_model(scenario, policy)
...

**Comment by stefaneidelloth** [comment]
After completly removing Vensim and reinstallig it, it works now. 
Also see
http://www.ventanasystems.co.uk/forum/viewtopic.php?f=2&t=6173&p=21823&hilit=installation+path#p21823
