### ISSUE TITLE
How to publish Vensim model to be compatible with EMA Workbench?

### ISSUE THREAD

**Issue by stefaneidelloth** [quaquel/EMAworkbench#56]
I am able to run the Vensim example with model.vpm. However, I am not able to adapt the example for my needs. 

If I just open model.mdl file in Vensim DSS 6.0b and re-published it as model.vpm ....
I already get some different behavior: When running the experiments, Vensim shows some dialog 
`New Name for Dataset`, asking me to select some file.

=>What are the correct options for the publishing dialog of Vensim, so that I get a compatible *.vpm file?
=> Anything other I need to consider when creating the *.vpm file? Is it for example ok to use variable names like "Änderung Umsetzungsrate InvPro", including umlauts and spaces?

![image](https://user-images.githubusercontent.com/12675339/55219096-460b4000-5204-11e9-9351-e50eff4d145f.png)

Should the Settings check box be deactivated? Should Additional files be empty?
Should the package type be different than Model?
ect.

**Comment by quaquel** [comment]
remove Current.vdf and any other files from additional files

it's been a while since I used this, but to my knowledge that is all that is needed. If not, let me know and I will check with some other users of the workbench with Vensim.

**Comment by stefaneidelloth** [comment]
Yes, now it works. (If someone else has issues with publishing, also make sure to close Jupyter because the .vpm file might be locked.)
