### ISSUE TITLE
Improve documentation of result structure?

### ISSUE THREAD

**Issue by stefaneidelloth** [quaquel/EMAworkbench#57]
I would find it helpful if the structure of the results would be explained in more detail, maybe with some further examples on how to access different aspects of the results.

What I could find so far:

A. https://emaworkbench.readthedocs.io/en/latest/indepth_tutorial/general-introduction.html?highlight=experiments%5B%27policy

>By default, the return of perform_experiments is a tuple of length 2. The first item in the tuple is the experiments. The second item is the outcomes. Experiments and outcomes are aligned by index. The experiments are stored in a numpy structured array, while the outcomes are a dict with the name of the outcome as key, and the values are in a numpy array.

B. https://emaworkbench.readthedocs.io/en/latest/ema_documentation/em_framework/evaluators.html
returns the experiments as a numpy recarray, and a dict with the name of an outcome as key, and the associated scores as numpy array. Experiments and outcomes are alinged on index.

If someone is quite new to python, like me, it might be astonishing that "an array can be used as a dictionary":

`experiments['policy']`

=>It might be helpful to show that the titles of the recarray can be accessed with
`experiments.dtype.names` and that it has for example following structure

`('x1', 'x2', 'scenario_id', 'policy', 'model')`

It might also be useful to show how to get all outcomes for the first experiment and how plot them, e.g. for TimeSeries results:

```
import pandas as pd
from matplotlib import pyplot as plt

keyList = list(outcomes.keys())
outcomeOfFirstExperiment = {key: values[0] for key, values in outcomes.items()}

df = pd.DataFrame(outcomeOfFirstExperiment)  
df.plot(x=keyList[0])
plt.show()   
```
   
In my opinion such small examples might help to easier understand the structure of the results. 

Related: https://github.com/quaquel/EMAworkbench/issues/54

**Comment by quaquel** [comment]
which version of the workbench do you use? I am close to releasing a major update where the experiments are stored in a pandas dataframe, rather than the obscure NumPy recarray. 

Also, have you seen the examples folder?

**Comment by stefaneidelloth** [comment]
a) I installed ema_wokbench with pip and use version 1.3.2.

b) Good to know about the major update! I want to give an intro to the ema_workbench to some colleagues and I'll wait until that update. In my opinion it makes more sense to improve the result structure itself then improving the doc for the "old" structure. Therefore, I close this ticket. Do you plan to provide an extra method, e.g. perform_experiments_new or a conversion function to not break existing code for processing results?

c) I saw the examples folder and found the examples helpful, even if some of them are still in python 2 code (e.g. iteritems vs items). I admit that I did not go through all of the examples. Many of them seem to be about defining experiments and how to execute them. Maybe It would make sense to split the examples in sub folders, e.g. "define experiments", "perform experiments", "evaluate results", "full examples", if that is applicabile.
