### ISSUE TITLE
conversion error in uncertainty related parameter specification

### ISSUE THREAD

**Issue by robcalon** [quaquel/EMAworkbench#58]
A very small issue related to specifying the names of uncertainty related parameters: 

When I specify model uncertainty parameters with Parameter(name = 'X', variable_name = 'Y') the evaluation of my experiments results in a 'ValueError: cannot convert float NaN to integer'. 
The error is resolved when I don't try to assign a different header name to the variable. It is also only related to the model uncertainties, as the name, variable_name specification does work when I specify model levers.

**Comment by quaquel** [comment]
can you give me a minimum working example that replicates the error, preferably using a python function for the model? Will save me time fixing this issue, which sounds to be quite minor.

**Comment by robcalon** [comment]
No problem at all, when I use the python example within the workbench I get the same error:

'''
Created on 20 dec. 2010

This file illustrated the use the EMA classes for a contrived example
It's main purpose has been to test the parallel processing functionality

.. codeauthor:: jhkwakkel <j.h.kwakkel (at) tudelft (dot) nl>
'''
from __future__ import (absolute_import, print_function, division,
                        unicode_literals)

from ema_workbench import (Model, RealParameter, IntegerParameter, ScalarOutcome, ema_logging,
                           perform_experiments)


def some_model(x1=None, x2=None, x3=None):
    return {'y': x1*x2+x3}


if __name__ == '__main__':
    ema_logging.LOG_FORMAT = '[%(name)s/%(levelname)s/%(processName)s] %(message)s'
    ema_logging.log_to_stderr(ema_logging.INFO)

    model = Model('simpleModel', function=some_model)  # instantiate the model

    # specify uncertainties
    model.uncertainties = [IntegerParameter(name = 'factor x', variable_name = "x1", lower_bound = 1, upper_bound = 10),
                           RealParameter("x2", -0.01, 0.01),
                           RealParameter("x3", -0.01, 0.01)]
    # specify outcomes
    model.outcomes = [ScalarOutcome('y')]

    results = perform_experiments(model, 100).

**Comment by quaquel** [comment]
tried your example but it does not produce an error with the 2.x version of the workbench (so update with pip if you are still on 1.x)
