### ISSUE TITLE
TypeError: real_decorator() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by stefaneidelloth** [quaquel/EMAworkbench#60]
After updating to version 2 I get following error when using my custom repast connector, that worked with version 1. I don't understand the error. Any hint what I could do?

[EMA.ema_workbench.em_framework.evaluators/INFO/MainProcess] performing 10 scenarios * 1 policies * 1 model(s) = 10 experiments
[EMA.ema_workbench.em_framework.evaluators/INFO/MainProcess] performing experiments sequentially
[EMA.ema_workbench.em_framework.experiment_runner/ERROR/MainProcess] real_decorator() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\EclipsePython\App\WinPython\python-3.7.2.amd64\lib\site-packages\ema_workbench\em_framework\experiment_runner.py", line 84, in run_experiment
    model.run_model(scenario, policy)
  File "D:\EclipsePython\App\WinPython\python-3.7.2.amd64\lib\site-packages\ema_workbench\util\ema_logging.py", line 158, in wrapper
    res = func(*args, **kwargs)
  File "D:\EclipsePython\App\WinPython\python-3.7.2.amd64\lib\site-packages\ema_workbench\em_framework\model.py", line 332, in run_model
    super(SingleReplication, self).run_model(scenario, policy)
  File "D:\EclipsePython\App\WinPython\python-3.7.2.amd64\lib\site-packages\ema_workbench\util\ema_logging.py", line 158, in wrapper
    res = func(*args, **kwargs)
  File "D:\EclipsePython\App\WinPython\python-3.7.2.amd64\lib\site-packages\ema_workbench\em_framework\model.py", line 178, in run_model
    self.model_init(policy)
TypeError: real_decorator() takes 1 positional argument but 2 were given

**Comment by quaquel** [comment]
what model are you using, any code you can share?

**Comment by quaquel** [comment]
I think it has to do with the @method_logger decorator. I cannot be sure unless I see all your code together, so could you attach a .py file with the relevant code?

**Comment by stefaneidelloth** [comment]
The attached zip files contains some example Jupyter Notebook, the repast connector and modified repast code. The repast model itself is not included. 

[matisseExampleExploratoryModelling.zip](https://github.com/quaquel/EMAworkbench/files/3131161/matisseExampleExploratoryModelling.zip)

I just verified that if I go back to version 1.3.2 with 

pip install ema_workbench==1.3.2

it works again. After 

pip install ema_workbench --upgrade

the decorator issue occurs. So maybe its a bug or some interface for the connector workflow has been changed and I would have to adapt my connector code to make it work again.

**Comment by quaquel** [comment]
easy fix:

in repast.py, change @method_logger to @method_logger(__name__)

at the top add:

```python
from ema_workbench.util.ema_logging import method_logger

_logger = get_module_logger(__name__)
```

background: in the V2 branch, I have moved from having a single logger for the entire library, to having loggers for each .py file. The latter is a python convention, hence the change. I want to keep the method_logger decorator, so this decorator needs to know which logger to use for each method it is decorating. I can do this through reflection, but this is very slow, hence the need to pass __name__ to the decorator. __name__ is a python magic that returns the name of the module (i.e. .py file)

**Comment by stefaneidelloth** [comment]
Yes, that did the trick. Thanks a lot.
