### ISSUE TITLE
upcoming jpype release

### ISSUE THREAD

**Issue by marscher** [quaquel/EMAworkbench#65]
Hi,

I'd like to invite you to test the upcoming jpype version prior we push the release on pypi and potentially have your users suffer from api changes we had to make. For instance strings are not automatically converted from java to python, if not explicitly desired.

pip install git+https://github.com/jpype-project/jpype@master should install a recent version.

Thanks for checking and reporting back with us.

Best regards

**Comment by quaquel** [comment]
I'll see what I can do once teaching ends early July

**Comment by marscher** [comment]
I think we will release shortly. Thank you anyways.
