### ISSUE TITLE
Boxenplot - A beautiful way to show the tails

### ISSUE THREAD

**Issue by shajeelwn** [quaquel/EMAworkbench#66]
If one wants to present lower quantiles of the outcome distribution, "seaborn.boxenplot" (https://seaborn.pydata.org/generated/seaborn.boxenplot.html) presents a very nice solution to visualize it. Thus I would propose to extend ema_workbench.analysis.plotting with boxenplot.

**Comment by quaquel** [comment]
should not be too difficult. It requires adding a field to the Density enum in plotting_util, and a plot_boxenplot helper function. Are there any specific keywords required?
