### ISSUE TITLE
please help for EMA (explatory modeling approach) script

### ISSUE THREAD

**Issue by mkbahri** [quaquel/EMAworkbench#68]
Hi,

I tried to use the EMA workbench but I could not get any display
after running the model. Please kindly help me.
I attach my script and an error message

![ema_problem](https://user-images.githubusercontent.com/52463931/60530283-b42a3c00-9cf8-11e9-8050-3b69e7849115.png)

**Comment by quaquel** [comment]
what documentation are you using? This is an outdated call signature. It should be

```python
experiments, outcomes = results

lines(experiments, outcomes)

```

**Comment by mkbahri** [comment]
I don't remember what documentation I am reading.
I think I am reading your paper.

After I follow up your reply "experiements, outcome = results",
all are working.

But,

I modified a previous script as follows:

"popModel.outcomes = [TimeSeriesOutcome('population'),
                                        TimeSeriesOutcome('popgrowth') ]"
fig, axes = lines(experiments, outcome, titles=None, group_by=None, outcomes_to_show=[('population', 'popgrowth')])

this one is **not working**.
Did I miss something?

**Comment by quaquel** [comment]
if growth rate is an uncertainty, it cannot be also an outcome. 

please use the documentation on read the docs. All your questions so far are answerable based on reading the documentation provided there. For further ideas, look at the example folder that is in the ema_workbench directory in you python installation folder.
