### ISSUE TITLE
NetLogo 6.0.4, cannot setup chooser to a specific value in EMA using Categorical Parameter or Constant

### ISSUE THREAD

**Issue by kenanxiao0118** [quaquel/EMAworkbench#69]
The chooser is called "global-search-strategy", and it can be chosen from three different global variables.

The NetLogo code works perfectly when running on NetLogo, however, when I set up the experiments using the Exploratory Modeling Workbench (EMA), which is developed based on PyNetLogo, jpype. And when I try to overwrite the default value of the global-search-strategy, it causes the above error. But if I use the default one (the last saved value of global-search-strategy) without overwriting, it works just fine.

I am not exactly sure which part of the NetLogo code causes the problem, since I set it up on EMA and it works just fine on pure NetLogo.

I am not exactly sure if it is the same type of issues #818

Here is just a piece of the code for set-up:

![image](https://user-images.githubusercontent.com/38436254/61408349-71926300-a8a5-11e9-9059-2093e9be86d2.png)

Here is the part of the Python code:
![image](https://user-images.githubusercontent.com/38436254/61408368-78b97100-a8a5-11e9-8576-1c841ecfc729.png)

The following is the error from the Python:

Screenshot 2019-07-17 10 29 47
![image](https://user-images.githubusercontent.com/38436254/61408375-7f47e880-a8a5-11e9-80d8-25e7d666ad4d.png)

Any help would be useful, thanks!

**Comment by quaquel** [comment]
can you run in using a sequential evaluator and with logging set to debug?

I am curious to see what the exact command is that triggers the error?

**Comment by kenanxiao0118** [comment]
I ask people in NetLogo community, they found that it might be the case that EMA/pyNetLogo passing the string value "search-strategy-flock" as a raw text into NetLogo, as opposed to as a string. After I changed it to a literal string, such as **"\"search-strategy-flock\""**, it worked.

By the way, in the design of EMA, is the setup procedure isn't getting run in your original model before setting the global variables?

Thanks for your quick reply!

**Comment by quaquel** [comment]
happy to hear it works after a slight change. I was thinking in a similar direction, hence the request for the debug level log messages which should contain the exact commands being send to netlogo. 

the logic is in netlogo.py:

```python

 # TODO:: point for speedup. Send all set commands in 1 go
        for key, value in experiment.items():
            try:
                self.netlogo.command(self.command_format.format(key, value))
            except jpype.JavaException as e:
                _logger.warning(
                    'variable {} throws exception: {}'.format(
                        key, str(e)))

        _logger.debug("model parameters set successfully")

        # finish setup and invoke run
        self.netlogo.command("setup")

```

so currently, I first set all variables, and than call setup. I am by no means an expert on netlogo, but in my experience so far this has always worked fine.
