### ISSUE TITLE
Prim pairs scatter plot figure configuration

### ISSUE THREAD

**Issue by robcalon** [quaquel/EMAworkbench#73]
Feature request to update the pair scatter plot function in Prim to customise the configuration of the figure.

**Comment by EwoutH** [comment]
This issue is related to #141, I'm going to look into it!

**Comment by EwoutH** [comment]
I'm planning on a big plotting deep dive in November, I will include this issue. This will likely be part of the 2.4.0 release.

**Comment by EwoutH** [comment]
This was partly implemented in #288.
