### ISSUE TITLE
Vensim Connector

### ISSUE THREAD

**Issue by SsadeghKh** [quaquel/EMAworkbench#74]
Hi
I'm working on my PhD thesis about HR planning and I want to use EMA-workbench tu run my vensim model. 
Vensim DSS is to expensive for me as a student.
Is there any solution to use Vensim PLE instead of Vensim DSS?
Thanks

**Comment by quaquel** [comment]
not with Vensim.

You might try to use pysd to convert your Vensim model into a pysd model and use pysd in combination with the workbench.

**Comment by SsadeghKh** [comment]
Dear Mr Kwakkel

thanks for your kind reply on my previous question. I use pysd to translate my model. 
In my model I have some subscripts. One of my subrange is mapped to another. when i run code, the following error occurs. 

"[MainProcess/INFO] performing 1 scenarios * 1 policies * 1 model(s) = 1 experiments
[MainProcess/INFO] performing experiments sequentially
[MainProcess/ERROR] Rule 'entry' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with '-> All but Newest' (line 1, column 62)."

![image](https://user-images.githubusercontent.com/62960897/89472047-cba5e500-d794-11ea-89d2-7a88e6e9c78e.png)

Could you please help me on this problem?

Thanks 
With Regards
