### ISSUE TITLE
connect a function that takes a dictionary as an input and returns two pandas' data frames to ema

### ISSUE THREAD

**Issue by saeedashraf** [quaquel/EMAworkbench#79]
Dear Dr. Jan H. Kwakkel
I am writing in connection with your paper entitled "The Exploratory
Modeling Workbench: An open-source toolkit for exploratory modeling,
scenario discovery, and (multi-objective) robust decision making". I'm
trying to implement the "eam workbench" in my study.

I have a Python function that takes a dictionary as an input and returns two pandas' data frames:

https://github.com/saeedashraf/snow-ski-resort-finance/blob/master/snowmodel_py/snow_model_v2_ema_workbench.ipynb

I'm wondering if there is this possibility to have data frames as outputs of
a function and controlling that in "eam workbench".

Thank you in advance and I appreciate your time and consideration.

**Comment by quaquel** [comment]
you can't have dataframes as output if you want to connect it to the workbench. 

There are 2 options:
1. Create your own Outcome class
2. Rewrite your code to work within the limits of the workbench.

I would suggest option 2. So, what is in the DataFrame? Rewriting it so it works with the workbench should be trivial. Most likely, a to_dict on the dataframe is all that is required.

**Comment by saeedashraf** [comment]
Thanks for the response. 

What about the input of a function? I want to give a dictionary as an input and give max and min (ranges) to each key-value. Can I do that? if yes would you please elaborate on that?

**Comment by quaquel** [comment]
I am not sure I understand. Please read the documentation and check the examples folder. In particular the various lake problem examples.
