### ISSUE TITLE
Problem in translating vensim model into pysd

### ISSUE THREAD

**Issue by SsadeghKh** [quaquel/EMAworkbench#84]
Dear Mr Kwakkel

thanks for your kind reply on my previous question. 
I use pysd to translate my model.
In my model I have some subscripts. One of my subrange is mapped to another. when i run code, the following error occurs.

"[MainProcess/INFO] performing 1 scenarios * 1 policies * 1 model(s) = 1 experiments
[MainProcess/INFO] performing experiments sequentially
[MainProcess/ERROR] Rule 'entry' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with '-> All but Newest' (line 1, column 62)."

![image](https://user-images.githubusercontent.com/62960897/89474592-4e31a300-d79b-11ea-8a7a-bff24f2461df.png)

Could you please help me on this problem?

Thanks
With Regards

**Comment by quaquel** [comment]
There is a weird corner case where stuff crashes if you run only a single experiment. Do you get the same error with 2 scenarios?

**Comment by SsadeghKh** [comment]
It seems there is a problem with PySD. I have tried with a simple model again. 

![image](https://user-images.githubusercontent.com/62960897/89788321-360faa00-db34-11ea-9589-4d4b75a36a14.png)

**Comment by SsadeghKh** [comment]
It seems there is a problem with PySD. I have tried it with a simple model. PySD can't read the model.

![image](https://user-images.githubusercontent.com/62960897/89789237-93582b00-db35-11ea-8e20-dd6cc5861602.png)

**Comment by quaquel** [comment]
pySD and subscripts don't always play nice so that seems the most likely cause. That is to be discussed with the makers of PYSD. Can't you interact with Vensim directly?

**Comment by SsadeghKh** [comment]
Thanks. I wrote problem to PYSD Makers. But I've not received answer yet. I will try to contact with Vensim.

**Comment by quaquel** [comment]
To be clear: I mean use the VensimModel that also comes with the workbench.
