### ISSUE TITLE
ema - vensim connector error using the vensim example model

### ISSUE THREAD

**Issue by ApfelLeo** [quaquel/EMAworkbench#86]
Dear Jan,

with the goal to evaluate a vensim model, I first tried to familiarize myself with the vensim connector via the vensim example provided in the ema package. However, several issues arose, of which not all could be resolved:

First, a few changes were needed to vensim_example.py to get up to date: see #85 
Nonetheless, it has troubles launching Vensim or initializing the model.
1. running the code results in a popup window: Vensim Error: Screenshot1
2. aborting the error causes a "ZeroDivisionError" since no values were assigned from the model (screenshots 2 and 3)

The setup:
Vensim 8.1.0, 64 bit, double precision
Python 3.7.1, 64 bit
EMA-workbench 2.08

![Screenshot1](https://user-images.githubusercontent.com/16577950/89782849-4a44ae80-db16-11ea-81a1-6016e38519c1.jpg)
![Screenshot2](https://user-images.githubusercontent.com/16577950/89782854-4add4500-db16-11ea-8edc-e8159de081a3.jpg)
![Screenshot3](https://user-images.githubusercontent.com/16577950/89782856-4b75db80-db16-11ea-87c6-d7b7fc409b41.jpg)
What is your take on this, any idea where I could look to fix this problem?

Kind regards,
Ingo

**Comment by quaquel** [comment]
I will try to replicate your error as soon as possible

**Comment by quaquel** [comment]
I have been unable to replicate your error. Have you tried reinstalling Vensim?

**Comment by quaquel** [comment]
issue was due to not using Vensim dss
