### ISSUE TITLE
number of scenarios  vs policies

### ISSUE THREAD

**Issue by saeedashraf** [quaquel/EMAworkbench#87]
Dear Jan,

I am using ema_workbench for exploring the tipping point in Ski resorts in Switzerland.
I have set up my model and I ran 6000 experiments (120 scenarios * 50 policies). I do have 6 model parameters and 2 levers. I'm wondering if chose a good set up(120, 50). Since when I check the lake problem as a benchmark I see you have 5 model parameters and 5 levers. However, the experiment set up is 1000 scenarios * 5 policies.

Is there any specific rule or guideline for the number of experiments, scenarios, and policies?

Regards,
Saeid

**Comment by quaquel** [comment]
you should always 'validate' this but there are no hard rules for determining this other than more is basically always better. 

One easy check is to repeat your experiments (so another 600 runs). If you analyse both datasets, do you get the same insights or not? If the insights are the same, 600 might be sufficient. If the insights are different, or inconclusive, you might need more runs. 

What is your runtime and are you using parallization?

**Comment by saeedashraf** [comment]
"ipyparallel" is installed and although I could run other codes parallel with my Jupyter notebooks, But I could not use
MultiprocessingEvaluator of ema_workbench.

![pp_1](https://user-images.githubusercontent.com/22497185/90023196-bb6d9880-dcb3-11ea-800e-4502b0b85fb1.PNG)

for each ski resort, I run 6000 experiments. 
6000 experiments take 18hrs. 
I do have 11 ski resorts

**Comment by quaquel** [comment]
multiprocessing within notebooks is a mess. I avoid it and just use .py files typically to generate my results and then do the analysis in notebooks. You could use the ipyparrallel evaluator instead if you want to stay within a notebook.

Since you seem to have 6 cores on your machine, substantial speedup might be possible

**Comment by saeedashraf** [comment]
Thanks for the suggestions. I'll do the same.
