### ISSUE TITLE
Convenience function for averaging over replications in outcomes array

### ISSUE THREAD

**Issue by steipatr** [quaquel/EMAworkbench#92]
Averaging over the stochastic replications of experiments is a common postprocessing task in EMA. I would like to contribute a convenience function for this to `utilities.py` called `average_replications`. It will take the mean of the replications of each experiment, reducing the dimensionality of the outcomes numpy array from *experiments x replications x timesteps* to *experiments x timesteps*.

This function would empower the fix for saving/loading results added in #72. If it would be useful, let me know and I will submit a pull request.

**Comment by quaquel** [comment]
sounds useful

happy to look at the pull request and develop it further if necessary.

**Comment by steipatr** [comment]
OK, working on this.
