### ISSUE TITLE
Convenience function for resampling time series in outcomes array

### ISSUE THREAD

**Issue by steipatr** [quaquel/EMAworkbench#93]
For models generating (many) time series, the outcomes array can be quite large and cumbersome. To alleviate this, the time series could be downsampled. I would like to contribute a convenience function for this to `utilities.py` called `resample_timeseries`. The dimensionality of the outcomes array will be preserved, but the *timesteps* dimension will be reduced by some user-specifiable factor.

This function would empower the fix for saving/loading results added in #72. If it would be useful, let me know and I will submit a pull request.

**Comment by quaquel** [comment]
I missed this feature request. Go ahead and implement it. Please make sure you start from the latest version of the 2.1 branch. 

Minor comment given the process_replications code, please check the numpy doc standard.

**Comment by steipatr** [comment]
Holding off on this for now. Just downsampling the time series is a trivial NumPy command which doesn't warrant its own function, I feel. To make the function useful beyond that, time series processing such as smoothing and upsampling/interpolating would be nice, but I'm not seeing yet how to do that in an intuitive and widely applicable way.

**Comment by quaquel** [comment]
fair enough
