### ISSUE TITLE
ScalarOutcome and ArrayOutcome not compatible with ReplicatorModel

### ISSUE THREAD

**Issue by steipatr** [quaquel/EMAworkbench#94]
#### ScalarOutcome
When running a model with replications and at least one scalar outcome, the following error is returned by `ScalarOutcome.process()`:

> EMAError: outcome s should be a scalar, but is <class 'list'>: [...]

This seems to happen because `ScalarOutcome.process()` checks whether what is returned from the model is actually a scalar as expected, but the Replicator has already put the individual replications into a list. A possible fix would be to first check whether the returned object is a list, and if so, check whether the first list entry is a scalar.

#### ArrayOutcome
Similarly, when running a ReplicatorModel with a 2-dimensional ArrayOutcome, the following error is returned:

> EMAError: can only save up to 2d arrays, this array is 3d

This one comes from `DefaultCallback._store_outcomes()`. The shape is "replications * dim1 * dim2". I'm not sure why 3d arrays aren't allowed, since running a model with replications and time series outputs also creates a 3d array (experiments * replications * time steps).

I feel these errors are conceptually related, since in both cases the returned object is checked after the replications have already been turned into a list. Might be possible to run the checks before the list of replications is made? I attached an example file that can generate both errors.

[Scalar-Array-Replicator-debug.zip](https://github.com/quaquel/EMAworkbench/files/5608166/Scalar-Array-Replicator-debug.zip)

**Comment by quaquel** [comment]
I don't think I agree. 

The outcome class specifies the kind of outcome for a given computational experiment, rather than an individual replication. Too my knowledge .process is called after any function has been applied to the data of the experiments. So in that function you can apply whatever aggregation you want over the replications.

**Comment by steipatr** [comment]
I am not looking at averaging replications yet, just trying to get scalar and array outcomes to work with replicated models.  I can see why you would check the type of scalar outcomes, but what is the purpose of checking whether an array outcome is higher-dimensional than 2D in the DefaultCallback?

**Comment by quaquel** [comment]
that is most likely an implementation detail because of the save functionality which cannot deal with higher dimensional numpy arrays

**Comment by steipatr** [comment]
Aaah OK. Would you consider moving this dimensionality check to the save function? That would:

1) put the check in the function which it protects.
2) make array outcomes compatible with replicated models.

**Comment by quaquel** [comment]
That is tricky because if you run your experiments through .py file, you might get the error after you have ran all your experiments. So, I prefer to have a check before you have generated a lot of data and spend compute time. 

That being said, ND arrays should be simply supported.
